ARG DOCKER_IMAGE=alpine:latest

FROM $DOCKER_IMAGE as builder

ARG OSSLSIGNCODE_VERSION

WORKDIR /work

# Dependencies
RUN apk add --update --upgrade --no-cache curl build-base openssl-dev curl-dev autoconf libgsf-dev git cmake  \
    && git clone https://github.com/mtrojnar/osslsigncode \
    && cd osslsigncode \
    && git checkout $OSSLSIGNCODE_VERSION \
    && mkdir build \
    && cd build \
    && cmake -S .. \
    && cmake --build . \
    && chmod +x osslsigncode

FROM $DOCKER_IMAGE

RUN apk add --update --upgrade --no-cache curl 

COPY --from=builder /work/osslsigncode/build/osslsigncode .

ENTRYPOINT [ "./osslsigncode" ]